services:
    php-fpm: &php
        build:
            context: ./php
            args: &php-build-args
                UID: $CONTAINER_USER_UID
                GID: $CONTAINER_USER_GID
        working_dir: /var/www/html
        volumes:
            - "${SRC_DIR}:/var/www/html:delegated"
            - user_home:/home/www-data:delegated

    nginx:
        build:
            context: ./nginx
            args:
                UID: $CONTAINER_USER_UID
                GID: $CONTAINER_USER_GID
        volumes:
            - "${SRC_DIR}:/var/www/html:delegated"
            - ./nginx/server.conf:/etc/nginx/conf.d/default.conf:ro
            - ./nginx/certificate.key.pem:/etc/nginx/certificates/certificate.key.pem:ro
            - ./nginx/certificate.crt.pem:/etc/nginx/certificates/certificate.crt.pem:ro
            - ./nginx/defaults.conf:/etc/nginx/defaults:ro
            - ./nginx/fastcgi_params.conf:/etc/nginx/fastcgi_params:ro
        links:
            - php-fpm
        expose:
            - 80
            - 443
        ports:
            - 8080:80
            - 443:443

    mysql:
        image: mysql:latest
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'programm'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'root'
        links:
            - php-fpm

volumes:
    user_home:
        driver: local
        name: user_home
    mysql:
        driver: local
        name: mysql
